#26: Feature/#26 chat
TU-CP18/cp18-app pull request #64
Opened 2019-02-02 14:16 UTC by clemenspeters

2019-02-05 17:11 UTC, nschoen commented
Let's merge the HomeScreen first, then rebase onto the master and then use our custom Alert component, which I updated to support `info` and `success` messages, to show notifications when the app is open.

2019-02-05 17:15 UTC, nschoen requested changes

2019-02-05 17:15 UTC, nschoen commented on helpers/api.js
> +const request = (method, url, bodyParams, queryParams, queryHeaders) => {
Name queryHeaders, just to header and set a default value via `headers = {}`

2019-02-05 17:15 UTC, nschoen commented on helpers/api.js
> +
Remove this and set the header value in the `options` object directly

2019-02-05 17:15 UTC, nschoen commented on helpers/api.js
> +const patch = (url, bodyParams, queryParams) => request('patch', url, bodyParams, queryParams, {});
Remove all empty object `{}` params. Rename queryHeaders to just `headers` please.

2019-02-05 17:31 UTC, calvinschmidt requested changes

2019-02-05 17:31 UTC, calvinschmidt commented on App.js
> +
We have methods for this in `helpers/lib.js`. Please use them.

2019-02-05 18:12 UTC, calvinschmidt requested changes

2019-02-05 18:12 UTC, calvinschmidt commented on App.js
>  chatStore.load();
This does not work if the user is not logged in and the userStore isn't initialized yet.

2019-02-05 18:12 UTC, calvinschmidt commented on App.js
> +    this.listenForNotifications();
It already asks for the notification if the user is still logged out. Please check here if the user is logged in.

2019-02-08 10:24 UTC, nschoen approved these changes

2019-02-08 11:10 UTC, calvinschmidt approved these changes

2019-02-08 11:10 UTC, calvinschmidt commented
Thanks for resolving, looks good now!

2019-02-08 11:10 UTC, merged